apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.postgres.namespace }}
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432