apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.postgres.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-admin-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-admin-secret
              key: password
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: postgres-data-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data-pv
        persistentVolumeClaim:
          claimName: postgres-data-pvc
      restartPolicy: Always