apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: {{ .Values.postgres.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.class }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}