FROM ubuntu

ENV DEBIAN_FRONTEND "noninteractive"
ENV TZ "America/New_York"

RUN set -x \
  && echo "Preparing system..." \
  && apt-get -y update \
  && apt-get -y install \
    curl \
    git \
    nginx \
    python3-dev \
    python3-pip \
    rclone \
  && rm -rf /var/lib/apt/lists/* \
  && pip3 install --upgrade pip

RUN set -x \
  && echo "Installing jupyter kernel..." \
  && pip3 install ipykernel \
  && python3 -m ipykernel install

{%- if os.path.isfile(os.path.join(appyter_path, 'deps.txt')) %}

ADD deps.txt /app/deps.txt
RUN set -x \
  && echo "Installing system dependencies from deps.txt..." \
  && apt-get -y update \
  && apt-get -y install $(grep -v '^#' /app/deps.txt) \
  && rm -rf /var/lib/apt/lists/* \
  && rm /app/deps.txt

{%- endif %}

{%- if os.path.isdir(os.path.join(appyter_path, 'deps')) %}

ADD deps/ /app/deps/
RUN set -x \
  && echo "Installing .dep files from deps/*..." \
  && dpkg -i /app/deps/*.deb || true \
  && apt-get -y update \
  && apt-get -y install -f \
  && rm -rf /var/lib/apt/lists/* \
  && rm -r /app/deps/

{%- endif %}

{%- if os.path.isfile(os.path.join(appyter_path, 'setup.R')) %}

ADD setup.R /app/setup.R
RUN set -x \
  && echo "Installing R..." \
  && apt-get -y update \
  && apt-get -y install r-base \
  && rm -rf /var/lib/apt/lists/* \
  && echo "Setting up R with setup.R..." \
  && R -e "source('/app/setup.R')" \
  && rm /app/setup.R

{%- endif %}

{%- if os.path.isfile(os.path.join(appyter_path, 'requirements.txt')) %}

ADD requirements.txt /app/requirements.txt
RUN set -x \
  && echo "Installing python dependencies from requirements.txt..." \
  && pip3 install -r /app/requirements.txt \
  && rm /app/requirements.txt

{%- endif %}

ARG appyter_version=git+git://github.com/Maayanlab/appyter.git
RUN set -x \
  && echo "Installing appyter..." \
  && pip3 install --upgrade ${appyter_version}

RUN set -x \
  && echo "Preparing user..." \
  && useradd -ms /bin/bash -d /app app \
  && chown -R app:app /app \
  && chmod og+rwx -R /var/lib/nginx /var/log/nginx

USER app
WORKDIR /app
EXPOSE 80
VOLUME /app/data

ENV PREFIX "/"
ENV HOST "0.0.0.0"
ENV PORT "80"
ENV DEBUG "false"

COPY --chown=app:app . /app

RUN set -x \
  && echo "Overriding appyter templates..." \
  && python3 /app/merge_j2.py /app /app/override /app

CMD [ \
  "appyter", \
  {%- if 'profile' in config['appyter'] %}
  "--profile={{ config['appyter']['profile'] }}", \
  {%- endif %}
  {%- if 'extras' in config['appyter'] %}
  {%- for extra in config['appyter']['extras'] %}
  "--extras={{ extra }}", \
  {%- endfor %}
  {%- endif %}
  "{{ config['appyter']['file'] }}" \
]
