apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: minio-admin-secret
  namespace: {{ .Values.namespace }}
spec:
  forceRegenerate: false
  data: {}
  fields:
    - fieldName: username
      encoding: base64
      length: '15'
    - fieldName: password
      encoding: base64
      length: '15'