apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command: [ "minio" ]
        args:
        - server
        - /data
        - --console-address=:9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-admin-secret
              key: username
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-admin-secret
              key: password
        - name: MINIO_SERVER_URL
          value: https://{{ .Values.ingress.host }}
        - name: MINIO_BROWSER_URL
          value: https://{{ .Values.console.ingress.host }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: minio-data-pv
          mountPath: /root/.minio
          subPath: config
        - name: minio-data-pv
          mountPath: /data
          subPath: data
      volumes:
      - name: minio-data-pv
        persistentVolumeClaim:
          claimName: minio-data-pvc
      restartPolicy: Always