apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9001