---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: keycloak-tls-transport
  namespace: {{ .Values.keycloak.namespace }}
spec:
  insecureSkipVerify: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: {{ .Values.keycloak.namespace }}
spec:
  secretName: keycloak-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.keycloak.ingress.host }}
  dnsNames:
  - {{ .Values.keycloak.ingress.host }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: {{ .Values.keycloak.namespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.keycloak.ingress.host }}`)
    services:
    - kind: Service
      name: keycloak
      namespace: {{ .Values.keycloak.namespace }}
      port: 8443
      scheme: https
      passHostHeader: true
      serversTransport: keycloak-tls-transport
  tls:
    secretName: keycloak-tls