{{- if ( index .Values "rbac" "create" ) -}}
{{- if ne (index .Values "watchNamespace") "*" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "keycloak-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "keycloak-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "keycloak-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}