{{- if index .Values "rbac" "create" -}}
{{- if eq (index .Values "watchNamespace") "*" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "keycloak-operator.fullname" . }}
roleRef:
  name: {{ template "keycloak-operator.fullname" . }}
  kind: ClusterRole
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: {{ template "keycloak-operator.serviceAccountName" . }}
{{- end -}}
{{- end -}}