{{ if .Values.certmanager.clusterissuer.selfsigned }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
  namespace: {{ .Values.certmanager.namespace }}
spec:
  selfSigned: {}
---
{{ end }}