{{ if .Values.certmanager.clusterissuer.selfsigned }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: {{ .Values.certmanager.namespace }}
spec:
  isCA: true
  secretName: ca-tls
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replication-allowed: "true"
      replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.certmanager.clusterissuer.selfsigned.commonName }}
  dnsNames:
  - {{ .Values.certmanager.clusterissuer.selfsigned.commonName }}
---
{{ end }}