{{ if .Values.certmanager.clusterissuer.letsencrypt }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Values.certmanager.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certmanager.clusterissuer.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-prod-tls
    solvers:
    - http01:
        ingress: {{ .Values.certmanager.clusterissuer.letsencrypt.ingress }}
---
{{ end }}