apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-cert
  namespace: {{ .Values.namespace }}
spec:
  secretName: mail-tls
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.domain }}
  dnsNames:
  - {{ .Values.domain }}
  - mail.{{ .Values.namespace }}.svc.cluster.local