apiVersion: v1
kind: Service
metadata:
  name: mail
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mail
  type: ClusterIP
  ports:
  - name: mail
    port: 587
    protocol: TCP
    targetPort: 587